version: "3"
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16   # Change the subnet to a non-overlapping range
          gateway: 172.18.0.1
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      PMA_HOSTS: db
    ports:
      - "4500:80"

  web:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
      - "443:443"
